pypr/pysph

- .travis.yml
- README.rst
- appveyor.yml
- docs/source/design/overview.rst
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/overview.rst
- docs/source/tutorial/circular_patch.rst
- docs/source/tutorial/circular_patch_simple.rst
- pysph/base/tests/test_ext_module.py
- pysph/examples/tests/test_examples.py
- pysph/tools/tests/test_jobs.py
- setup.py
Also update the badges to point to appropriate builds.
> Fix README urls to point to gh.

- pysph/examples/dam_break_2d.py
- pysph/examples/taylor_green.py
- pysph/sph/wc/edac.py
Add new EDAC scheme but this is still experimental, use at your own risk.
> Edac scheme

- docs/source/design/solver_interfaces.rst
- docs/source/pyzoltan/overview.rst
- docs/source/tutorial/circular_patch_simple.rst
- docs/source/using_pysph.rst
> Make docs python3 compatible.

- pysph/tools/gmsh.py
Fix a bug float to int that failed cause failure in dam_break_3d before.
> Float to int division

- pysph/tools/ipython.py
3D still needs some work, 2D is done with the additional options of particle size, vector scale and save as pdf.
> Jupyter Notebook Viewer 2D 

- docs/source/design/overview.rst
Getting my feet wet by fixing a tiny typo.
> Fixed it's/its

- pysph/sph/scheme.py
- pysph/tools/mayavi_viewer.py
- Fix pressure wall condition when using multiple fluids.
- Fix viewer issues when number of particles changes.
> Misc fixes

- pysph/examples/periodic_cylinders.py
- pysph/examples/periodic_tunnel.py
This uses inlets and outlets, the TVF scheme, and simulates flow past a
circular cylinder.  The problem is periodic in the y-axis.
> Adding a simple wind tunnel example.

- pysph/examples/run.py
- pysph/examples/sphysics/beach_geometry.py
- pysph/tools/geometry.py
- pysph/tools/tests/test_geometry.py
Added arguments for number of layers for get_2d_tank and get_2d_wall functions and started test functions for geometry.
> Geometry module commits

- pysph/tools/ipy_viewer.py
- Added a colormap dropdown option with all possible colormaps to choose from
- Emboldened particle array names, added borders and margin
- Added a horizontal overscroll bar
> 2D ipy_viewer enhancements 

- pysph/tools/ipy_viewer.py
The 3D viewer currently supports:
1) ipyvolume scatter (any output property) and quiver plots (for <u,v,w> )
2) Changeable colormaps for scatter plots and corresponding legends
3) Changeable glyph sizes for both scatter and vector plots 
----------
--------------
> Added 3d Jupyter Notebook Viewer

- pysph/tools/geometry.py
- pysph/tools/tests/test_geometry.py
Vectorising checks in geometry and test_geometry to reduce the time taken to generate the geometry
> Changes in geometry and test_geometry

- pysph/base/tests/test_translator.py
- pysph/base/translator.py
- pysph/base/utils.py
- pysph/solver/application.py
- pysph/sph/acceleration_eval_opencl.mako
- pysph/sph/acceleration_eval_opencl_helper.py
- pysph/sph/tests/test_acceleration_eval.py
This adds support for:
- sub-groups inside a group, 
- iterated groups 
- converged call for iterations
- using printf in opencl for debugging.
> OpenCL phase2 of changes

- appveyor.yml
- pysph/base/translator.py
- pysph/examples/rigid_body/dam_break3D_sph.py
- pysph/examples/rigid_body/solid_body_floating_in_tank.py
- pysph/examples/sphysics/case8.py
- pysph/sph/acceleration_eval_opencl.mako
- pysph/sph/boundary_equations.py
- pysph/sph/gas_dynamics/basic.py
- pysph/sph/rigid_body.py
- pysph/sph/solid_mech/basic.py
- pysph/sph/wc/basic.py
- shippable.yml
- tox.ini
- Bug in equations with no sources, this was using the wrong group.
- Better error for unsupported Python code in translator.
- Bug in sphysics/case8.
- Handle some edge cases where we had max(float, double) by defining a
macro.
- Fix a few pi variables to p_i.
> Fix a few miscellaneous bugs.

- pysph/examples/run.py
- pysph/tools/geometry.py
Changed the element to points in show_3d function.
> Fixed show_3d in geometry

- pysph/base/gpu_domain_manager.py
- pysph/base/gpu_nnps_base.pyx
- pysph/base/gpu_nnps_helper.py
- pysph/base/opencl.py
- pysph/sph/acceleration_eval_opencl_helper.py
- pysph/sph/integrator_opencl_helper.py
The OpenCL support was not working on Python3.
> Py3 opencl fixes

- pysph/base/gpu_nnps_base.pyx
- pysph/base/stratified_sfc_gpu_nnps.mako
- pysph/base/z_order_gpu_nnps.mako
Gives a 10% improvement for ZOrderGPUNNPS
> Minor optimizations for OpenCL NNPS

- pysph/base/c_kernels.pyx.mako
The back slashes were not working on Windows.
> Fix error on Windows.

- pysph/base/nnps_base.pyx
- pysph/base/tests/test_periodic_nnps.py
Thanks to @sankasuraj for the test cases and @nilsmeyerkit for the fix.  Fixes #49
> Fix periodicity along z-axis.

- docs/source/installation.rst
Some additional details on how to get PySPH running on a Linux machine with ICC.
> ICC documentation

- docs/source/design/equations.rst
- docs/source/design/overview.rst
- docs/source/index.rst
Also explain how the equations are used in greater detail.
> Gather equation related docs in one place.

- pysph/solver/vtk_output.py
Hi,
I noticed that 'dump_vtk' fails for some cases when using TVF. I suggest the following fixes for this issue.
Nils
> Small fixes in VTK export

- pysph/solver/vtk_output.py
I just realized that I did not test VTK export with given sclarars using the option "-s ...". This, obviously, needs the missing 'else' statement.
Sorry for the inconvinience and not providing tests.
> Added missing 'else' statement in VTK export.

- docs/source/tutorial/circular_patch_simple.rst
- pysph/tools/ipy_viewer.py
- ipympl backend is now mandatory
> 2d viewer fix - modified the code to work with ipympl backend

- pysph/base/cython_generator.py
- pysph/base/tests/test_cython_generator.py
> Allow commented declare lines in Cython.

- pysph/base/tests/test_translator.py
- pysph/base/translator.py
> ENH: Support ternary operators while transpiling.

- docs/source/design/equations.rst
- docs/source/design/overview.rst
- pysph/parallel/tests/simple_reduction.py
- pysph/sph/acceleration_eval_opencl_helper.py
- pysph/sph/equation.py
- pysph/sph/gas_dynamics/basic.py
- pysph/sph/iisph.py
- pysph/sph/rigid_body.py
- pysph/sph/tests/test_acceleration_eval.py
This changes the API for reduce though.
> Reduce pass t dt

- pysph/sph/acceleration_eval_cython_helper.py
- pysph/sph/acceleration_eval_opencl_helper.py
- pysph/sph/tests/test_acceleration_eval.py
Given the increasing number of helper functions used in equations, we
now generate the helper code better to prevent repeated definitions
resulting in compilation errors.  Equations can therefore be safely
repeated and can reuse existing helpers.
> Allow repeated helper functions.

- pysph/examples/surface_tension/circular_droplet.py
- pysph/examples/surface_tension/khi_sy11.py
- pysph/examples/surface_tension/khi_tvf.py
- pysph/examples/surface_tension/square_droplet.py
- pysph/sph/surface_tension.py
Removed post loop of Smoothed Color Equation. If users don't want to smooth color in the problem, don't use Smoothed Color Equation.
> Change in Smoothed Color Equation in Surface Tension

- pysph/cpy/api.py
- pysph/cpy/ast_utils.py
- pysph/cpy/cython_generator.py
- pysph/cpy/extern.py
- pysph/cpy/low_level.py
- pysph/cpy/tests/test_ast_utils.py
- pysph/cpy/tests/test_low_level.py
- pysph/cpy/tests/test_transpiler.py
- pysph/cpy/transpiler.py
- Adds a low-level Cython class to easily execute code via Cython.
- Add support for defining constants in the global namespace and automatically using them.
- Add support for external libraries which opens up many interesting possibilities.
> Add low level Cython support and support for external libraries

- examples/cpy/README.rst
- pysph/cpy/api.py
> Add a lot more useful documentation.

- pysph/cpy/parallel.py
- pysph/cpy/tests/test_parallel.py
We still need to add a Cython version.
> Add a simple wrapper for the PyOpenCL scan.

- pysph/base/c_kernels.pyx
- pysph/base/kernels.py
- pysph/cpy/tests/test_translator.py
- pysph/cpy/translator.py
- pysph/sph/equation.py
> Kernel fix

- pysph/base/tests/test_device_helper.py
- pysph/base/tests/test_particle_array.py
- pysph/cpy/cuda.py
- pysph/cpy/parallel.py
- pysph/cpy/tests/test_array.py
- pysph/cpy/tests/test_parallel.py
- pysph/cpy/transpiler.py
I don't know if there will be any licensing issues with this
> Add CUDA scan support to CPy (temporary)

- docs/source/design/equations.rst
> Some minor documentation fixes.

- pysph/examples/taylor_green.py
- pysph/solver/tools.py
- Improves the simple remesher so the equations can be set by the user.
- Add M4 based remeshing to taylor green example which works very well.
- Will eventually change the remeshing after more exploration.
> Some improvements to remeshing

- pysph/examples/taylor_green.py
- pysph/sph/scheme.py
- pysph/sph/tests/test_kernel_corrections.py
- pysph/sph/wc/crksph.py
- pysph/sph/wc/kernel_correction.py
- pysph/tools/mayavi_viewer.py
- pysph/tools/sph_evaluator.py
Fix the kernel correction implementation for Bonet and Lok.  Also fix the taylor green problem so this works.
> Correct corrections

- pysph/examples/taylor_green.py
- pysph/solver/tools.py
- pysph/sph/iisph.py
Also fixes a subtle bug with the remeshing -- the domain was not being
updated after the remesh, which we now do.
> Get IISPH working with periodic problems.

- pysph/sph/equation.py
"eqn_info" is set using a list variable, so for multi stage equations this needs to be changed.
> add __repr__ to MultiStageEquations

- pysph/sph/rigid_body.py
> Fix body force equation for rigid body.

- pysph/solver/application.py
- pysph/solver/solver.py
The MultiStageEquation `__iter__` method may not be clean, any suggestions?
> clean-up logging code, include kernel and particle info.

- pysph/examples/taylor_green.py
- pysph/sph/wc/shift.py
This is added to maintain better uniform
distribution of particles.
> Add particle position shift.

- docs/source/design/equations.rst
- docs/source/installation.rst
- docs/source/tutorial/circular_patch_simple.rst
- pysph/solver/application.py
- Document Application's attributes.
- Document the Group better.
- Update installation instructions based on some of the recent changes.
> Update some docs

- pysph/tools/interpolator.py
- pysph/tools/mayavi_viewer.py
- pysph/tools/tests/test_interpolator.py
- Add support to perform plain SPH interpolation and not Shepard interpolation.
- Mayavi viewer now uses the SPH interpolation.
> Minor changes to interpolator

- docs/source/installation.rst
Also add ubuntu 18.04 specific instructions thanks to Alomir.
> Document issues with pip's cache.

- pysph/tools/mayavi_viewer.py
> Fix some old Python2 specific code.

- pysph/examples/spheric/moving_square.py
- pysph/tools/ipy_viewer.py
Added the play button, linked it to the slider and the delay input box.
> Added the play button and the 'Delay' input for the 2D jupyter notebook viewer.

- pysph/sph/gas_dynamics/gsph.py
This was incorrect earlier, sstar was not being computed for the cubic
interpolation.
> GSPH: Correct value for sstar.

- pysph/base/gpu_domain_manager.py
- pysph/base/nnps_base.pxd
- pysph/base/nnps_base.pyx
- pysph/base/particle_array.pxd
- pysph/base/particle_array.pyx
- pysph/base/tests/test_periodic_nnps.py
- Fix bug when nnps with periodicity is updated after properties are added to the particle arrays.
- Support for only copying some properties for periodicity -- doesn't make a big performance difference.
> Periodicity fixes

- pysph/examples/gas_dynamics/blastwave.py
- pysph/examples/gas_dynamics/riemann_solver.py
- pysph/examples/gas_dynamics/robert.py
- pysph/examples/gas_dynamics/shocktube.py
- pysph/examples/gas_dynamics/shocktube_setup.py
- pysph/examples/gas_dynamics/sjogreen.py
- pysph/examples/gas_dynamics/sod_shocktube.py
- pysph/examples/gas_dynamics/wallshock.py
- pysph/sph/scheme.py
-  fix examples for Kunal (2014)
-  fix mpm not using adaptive_h_scheme and add wallboundary 
-  fix riemann_solver.solve not accounting for initial discontinuity position
> Fix Gas Dynamics issues

- pysph/tools/mayavi_viewer.py
A simple UI so one can view the scalar components of any strided
properties in the Mayavi viewer.
> Support for viewing components of strided props.

- pysph/tools/ipy_viewer.py
Debugged and updated the 3D viewer, added the 'save all plots' option to the 2D viewer.
> Fixed the 3D viewer, added the 'save all plots' option to the 2D viewer

- pysph/examples/solid_mech/impact.py
- pysph/examples/solid_mech/impact3d.py
- pysph/examples/solid_mech/oscillating_plate.py
- pysph/examples/solid_mech/rings.py
- pysph/examples/solid_mech/taylor_bar.py
- pysph/sph/solid_mech/basic.py
1. Wrote scheme for trivial elastic dynamics.
2. Added oscillating plate example.
3. Moved rings example to scheme.
4. Changed hvi examples to new equations. 
5. Pep 8 fixes on rings, oscillating_plate, and basic.py files.
> Solids sph

- pysph/examples/sphysics/dam_break.py
Make the case5 consistent with the paper.
> Add a handy case for comparison.

- pysph/base/nnps_base.pyx
- pysph/solver/application.py
- pysph/solver/solver.py
- This can be convenient and may improve some performance.
> Fix bug in spatial ordering and add option for it.

- pysph/examples/dam_break_2d.py
- Use --dx and --hdx instead of the strange --h-factor.
- Add a --staggered-grid instead of hard-coding it for wcsph.
> Clean CLI of dam_break_2d example.

- pysph/examples/dam_break_3d.py
The obstacle was not seen, change number of boundary particles, and use
slightly higher hdx, also add hdx as a command line parameter.
> Fix some issues with the dam break 3d example.

- pysph/sph/tests/test_linalg.py
- pysph/sph/wc/crksph.py
- pysph/sph/wc/density_correction.py
- pysph/sph/wc/linalg.py
- pysph/tools/interpolator.py
- pysph/tools/mayavi_viewer.py
- pysph/tools/tests/test_interpolator.py
The interpolator doesn't give gradients in the current version.
> added gradient interpolation

- pysph/examples/dam_break_2d.py
- pysph/examples/dam_break_3d.py
To make it compatible with DTSPH paper.
> Add dt to WCSPH in DB2D and output times to DB3D.

- pysph/tools/ipy_viewer.py
Added a 'component' IntBox in the notebook viewer to allow users to view components of strided arrays.
> Added support for strided arrays in the notebook viewer.

- pysph/base/z_order_gpu_nnps.pyx
The log function needs to be imported on Windows.  Thanks to Randy
Meijer for spotting this error.
> Fix bug on Windows.

- pysph/examples/gas_dynamics/accuracy_test_2d.py
- pysph/examples/gas_dynamics/acoustic_wave.py
- pysph/examples/gas_dynamics/cheng_shu_1d.py
- pysph/examples/gas_dynamics/riemann_solver.py
- pysph/examples/tests/test_examples.py
- pysph/sph/gas_dynamics/basic.py
- pysph/sph/gas_dynamics/gsph.py
- pysph/sph/gas_dynamics/riemann_solver.py
- pysph/sph/scheme.py
- minor fixes in GSPHAcceleration
- copy properties to periodic ghosts in GSPHScheme
- add acoustic wave diffusion examples (1 and 2-D)
- expose density iteration parameters in GasDScheme (MPM)
- fix small bug with vsig calculation in MPMAcceleration
> Gas dynamics fixes

- pysph/sph/equation.py
__len__ returns the number of groups in a multi stage equation.
> Indent equations in log file add __len__ to MultiStageEquations

- pysph/base/tests/test_utils.py
- pysph/base/utils.py
- pysph/solver/application.py
- Fix bug in checking for overridden method.
- Set global config options early.
> Bug fixes.

- pysph/solver/solver_interfaces.py
- pysph/tools/mayavi_viewer.py
- Fix issue with authkey not accepting strings (for the live mode or when using the multiprocessing solver interfaces).
- Add support for using a formula for scalars and vectors.
- Cleanup the UI layout to be more compact.
- Add support for setting the scalar range.
- Add options to set the point size and opacity directly.
- Button to set the colormap with fewer clicks.
- Check that the live UI works.
- Honor the mayavi_config in live mode.
> Improve mayavi viewer

- pysph/solver/application.py
- pysph/solver/tests/test_application.py
- pysph/tools/mayavi_viewer.py
- Fix viewer bugs with the scalar range, show_vectors was not working the first time, show vectors was resetting the zoom.
- Application.read_info did not set the right output_dir.  Fix issue with annoying pytest_output directory when running tests.
- Made viewer more robust to deleted files and directories.
> Fix many miscellaneous bugs

- pysph/tools/mayavi_viewer.py
- The timer API has changed and is also broken so we work around it.
- Add support in the viewer to step by n steps instead of viewing each
file when playing the saved files.
> Fix to support pyface-6.1.1, support steps.

- pysph/solver/application.py
- pysph/sph/acceleration_eval_cython.mako
- pysph/sph/integrator_cython.mako
- pysph/sph/integrator_cython_helper.py
- pysph/sph/integrator_gpu_helper.py
- pysph/sph/tests/test_integrator.py
- Add support for helpers in itegrators. Allows a user to use `_get_helpers_` for integrator steps.
- Also add support for `address` in Cython.
- Add --post-process command line arg to `Application`.
> Misc improvements

- pysph/examples/taylor_green.py
- pysph/sph/isph/isph.py
- Divergence free formulation of ISPH is implemented
- Currently only fluids are supported.
> Added basic ISPH implementation.

- pysph/sph/integrator.py
Sometimes in inlet/outlet/fluid we may have zero particles. There without checking the particle size going for min of the array will gice error.
> added check particle array size

- pysph/tools/mayavi_viewer.py
This works on the Mayavi viewer.
> Allow users to use constants in formulae.

- pysph/examples/cavity.py
- pysph/examples/poiseuille.py
- Put setup_properties after m, rho gets initialized.
> Fix normals for cavity & exact sol for poiseuille

- docs/source/installation.rst
- setup.py
Support for using clang with OpenMP.  Also update instructions for this.
> Clang OpenMP

- pysph/base/kernels.py
- pysph/base/tests/test_kernel.py
- pysph/solver/utils.py
- pysph/solver/vtk_output.py
- It was not handling a non-existent directory.
- Mishandled cases where the output directory is specified.
- Also fix issues with the get_files method and clean it up.
- Also fix the quintic spline kernel factor in 3D.
> Fix dump vtk path

- pysph/solver/application.py
- pysph/sph/equation.py
- Log the pre-post_step and post_stage callbacks.
- Improve formatting of groups and equations so it is more readable.
- Some minor improvements to the logging as well.
> Improve logging

- pysph/base/nnps.py
- pysph/base/octree_nnps.pxd
- pysph/base/octree_nnps.pyx
- pysph/base/stratified_sfc_nnps.pxd
- pysph/base/stratified_sfc_nnps.pyx
- pysph/base/tests/test_nnps.py
- pysph/base/z_order_nnps.pxd
- pysph/base/z_order_nnps.pyx
Duplicating #253 as it had way too many conflicts while rebasing
> Add extended uniform grid and use arrays instead of maps for NNPS

- pysph/solver/output.py
- pysph/solver/tests/test_solver_utils.py
The logic was reversed and not all attributes/constants were compressed.
> Fix bug in compressed hdf5 files.

- pysph/tools/interpolator.py
- pysph/tools/tests/test_interpolator.py
Added type and stride info while merging the props. Currently strides cannot be interpolated.
> Fix issue with merging props in interpolator.

- pysph/base/nnps_base.pxd
- pysph/base/tests/test_particle_array.py
- pysph/base/utils.py
- pysph/examples/_db_geometry.py
- pysph/examples/dam_break_3d.py
- pysph/parallel/parallel_manager.pyx
- pysph/parallel/tests/example_test_case.py
- pysph/parallel/tests/lb_exchange.py
- pysph/parallel/tests/test_parallel_run.py
- pysph/solver/application.py
- pysph/solver/solver.py
- pysph/sph/acceleration_eval_cython.mako
- pysph/sph/acceleration_eval_gpu_helper.py
- pysph/sph/integrator.py
- pysph/sph/integrator_cython.mako
- pysph/tools/run_parallel_script.py
- BUG: particles_info was not saving lb_props this would cause problems in parallel.
- BUG: Fix a subtle bug when running in parallel with lb_props.
- ENH: add profiling support at a high level.
- BUG/ENH: Write info file only on master and dump profile info into CSV file.
> Fix some bugs in parallel manager and add profiling info

- pysph/solver/application.py
Also improve some of the parallel options with choices.
> ENH: Gather profile info into one file.

- pysph/examples/gas_dynamics/riemann_solver.py
- pysph/examples/gas_dynamics/sod_shocktube.py
- pysph/sph/scheme.py
- Before both solids and mirror bc are set which is incorrect.
- Solid support is removed as mirror bc is sufficient for this problem.
> Fix bugs in sod shocktube.

- pysph/tools/binder.py
- Fix bug with recursion error on nested output directories.
- Do not clobber existing readme/requirements or notebooks.
- Improve the requirements and default readme a little.
> Some fixes to the binder command.

- docs/source/installation.rst
- docs/source/reference/tools.rst
- pyproject.toml
- pysph/solver/application.py
- pysph/sph/basic_equations.py
- pysph/sph/bc/inlet_outlet_manager.py
- pysph/sph/gas_dynamics/basic.py
- pysph/sph/integrator.py
- pysph/sph/solid_mech/basic.py
- pysph/sph/surface_tension.py
- pysph/sph/tests/test_acceleration_eval.py
- pysph/sph/tests/test_integrator.py
- pysph/sph/tests/test_multi_group_integrator.py
- pysph/sph/wc/gtvf.py
- pysph/sph/wc/viscosity.py
- pysph/tools/interpolator.py
- pysph/tools/read_mesh.py
- setup.py
- tox.ini
- Always build opencl extensions, so our wheels are OK with or without it being available.
- Improve build configurability by using the `~/.compyle/config.py`.
- Improve installation docs a bit.
- Fix misc. sphinx errors.
- Add pyproject.toml
> Improve builds and configurability

- pysph/solver/application.py
- pysph/solver/utils.py
Earlier progressbars would not render on notebooks since stdout is not a
tty.  This is now fixed.
> Fix progressbar on jupyter notebooks.

- pysph/base/stratified_hash_nnps.pyx
Fix a division by 0 bug in stratified hash nnps. Fixes #237
> Skip empty levels in stratified hash nnps

- .github/workflows/tests.yml
- pysph/base/gpu_helper_kernels.py
- pysph/sph/acceleration_eval_gpu_helper.py
Also fixes all CUDA/OpenCL tests.
> Enable OpenCL tests on gh actions.

- docs/source/design/iom.rst
- docs/source/examples/flow_past_cylinder.rst
- docs/source/examples/index.rst
- docs/source/index.rst
- pysph/examples/flow_past_cylinder_2d.py
- pysph/sph/wc/crksph.py
Added documentation for inlet outlet
Small fix in crksph and fpc
> Added documentation for inlet outlet

- docs/source/conf.py
This change is same with enthought/mayavi#777 .
> 📝 Fix for L10N sphinx document

- pysph/base/octree.pxd
- pysph/base/octree.pyx
- pysph/base/octree_nnps.pxd
- pysph/base/octree_nnps.pyx
- pysph/base/tests/test_nnps.py
- pysph/base/tests/test_octree.py
One thread launch parallel algorithm for Octree and Compressed Octree. Also fixed memory leak in the algorithm.
> Improved Parallel Algorithm for Octree and Compressed Octree 

- CHANGES.rst
- pysph/__init__.py
- pysph/parallel/tests/test_parallel.py
Also fix #326 by increasing timeout.
> Release branch for PySPH-1.0b1.

- .github/workflows/tests.yml
- .github/workflows/zoltan-tests.yml
- cache auto-generated code in ~/.pysph and ~/.compyle
- refresh cache key monthly
- new monthly cron job
> ci(gh actions): add caching

- Makefile
- pysph/base/cell_indexing_nnps.pyx
- pysph/base/stratified_sfc_gpu_nnps.pyx
- pysph/base/stratified_sfc_nnps.pyx
- pysph/base/z_order_gpu_nnps.pyx
Also fix a missing directory in the Makefile.
> Try and fix Windows build failures.

- pysph/tools/ipy_viewer.py
Cull factor was not initialized correctly.
> Fixes #352.

- pysph/examples/gas_dynamics/shocktube.py
- pysph/sph/gas_dynamics/magma2.py
- pysph/sph/gas_dynamics/psph.py
- pysph/sph/gas_dynamics/tsph.py
- pysph/sph/scheme.py
- fixed some errors in PSPH, TSPH and MAGMA2
- GSPH can accept string arguments for rsolver, monotonicity and interpolation choices now
- initial spacing can now be given as command line argument for shocktube_2d example
> Minor fixes and enhancements

- pysph/tools/mayavi_viewer.py
The unicode characters show up in windows but they are blue.
> Added playback buttons to viewer

- .github/workflows/tests.yml
- .github/workflows/zoltan-tests.yml
- pysph/base/tests/test_device_helper.py
Followed this: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
> fix(tests): nose deprecation

- .gitignore
- pysph/sph/acceleration_eval_gpu_helper.py
This can cause performance improvements depending on the usage. This
mirrors the recent change in compyle.
> Some gpu improvements

- pysph/solver/application.py
- pysph/tools/dump_xdmf.py
- pysph/tools/interpolator.py
- pysph/tools/mayavi_viewer.py
- pysph/tools/tests/test_dump_xdmf.py
- pysph/tools/tests/test_interpolator.py
Fixes and enhancements to:
- solver
- viewer
- interpolator
- dump_xdmf
> Fixes and enhancements

- .github/workflows/tests.yml
- .github/workflows/zoltan-tests.yml
- not using setup.py develop anymore.
> Github Actions Green
