pysph/base/tests/test_translator.py
pysph/base/translator.py
pysph/sph/acceleration_eval_cython.mako
pysph/sph/acceleration_eval_opencl.mako
pysph/sph/acceleration_eval_opencl_helper.py
pysph/sph/integrator_opencl_helper.py
pysph/sph/tests/test_acceleration_eval.py

First round of multiple improvements to OpenCL support.
- Prettify the generated code a bit.
- Add more math constants.
- Support printf in cython (works with openmp!)
- Support for real=True and update_nnps in OpenCL.

Opencl improvements round 1

---

pysph/base/gpu_nnps_base.pyx
pysph/base/gpu_nnps_helper.py
pysph/base/tests/test_nnps.py
pysph/base/z_order_gpu_nnps.mako
pysph/base/z_order_gpu_nnps.pyx

I've added a test for finding neighbors multiple times.
The tests will fail because of ZOrderGPUNNPS

Fix BruteForceNNPS and ZOrderGPUNNPS for multiple particle arrays

---

pysph/sph/acceleration_eval_opencl.mako
pysph/sph/acceleration_eval_opencl_helper.py
pysph/sph/wc/edac.py

- The edac equation was using the variable pi which will not work with
OpenCL as pi is already defined.  Fixing this.
- Defining pi as __constant in OpenCL.
- Turn off warnings in OpenCL compilation as it makes it very hard to
find the real errors.

Fix a few miscellaneous issues.

---

docs/source/installation.rst
pysph/base/config.py
pysph/base/tests/test_config.py
pysph/solver/application.py
pysph/sph/acceleration_eval_cython.mako
pysph/sph/acceleration_eval_cython_helper.py

Allow users to specify which OpenMP schedule to use through the `--omp-schedule` parameter. The default value is set to `dynamic` with a chunksize of `64`.

OpenMP Schedule

---

pysph/sph/scheme.py

When there is no hg correction we should still run the tait eos on
solids in order to set the pressure but this was not being done leading
to a lot of leakage on the solids.  This is now fixed.

BUG: Fix bug with the WCSPH scheme.

---

docs/source/design/equations.rst
pysph/base/cython_generator.py
pysph/base/tests/test_translator.py
pysph/base/translator.py
pysph/sph/acceleration_eval_cython.mako
pysph/sph/acceleration_eval_cython_helper.py
pysph/sph/acceleration_eval_opencl.mako
pysph/sph/acceleration_eval_opencl_helper.py
pysph/sph/equation.py
pysph/sph/tests/test_acceleration_eval.py

Add support for a `loop_all` method in the equations.   This also adds support to pass the SPH kernel to equations and be able to call their kernel or gradient method.  Adds documentation and tests for this.  This works fine on both CPU and GPU.  This allows for more complex computations with the neighboring particles including non-pairwise interactions!  Paves the way for MD and other methods.

Add loop all

---

pysph/examples/gas_dynamics/shocktube_setup.py
pysph/examples/gas_dynamics/sod_shocktube.py
pysph/sph/gas_dynamics/basic.py
pysph/sph/gas_dynamics/gsph.py
pysph/sph/gas_dynamics/riemann_solver.py
pysph/sph/integrator_step.py
pysph/sph/scheme.py
pysph/sph/tests/test_riemann_solver.py

This adds several things:
- Adds around 11 different Riemann solvers including the exact to pysph such that it should work out of the box as well as 10 other approximate Riemann solvers.  This can be used for other things too.
- Adds the GSPH scheme with a suitable scheme/stepper etc.
- Updated the sod shocktube example to work with GSPH.
- This ports the most difficult scheme from sph2d to pysph.

Add the GSPH schemes including the ones from Kunal's paper

---

pysph/sph/acceleration_eval.py
pysph/sph/tests/test_acceleration_eval.py

Currently this was preserved for the loops but not for the
initialize/post_loop/reduce etc.  This is technically a problem as we
are supposed to guarantee the order.  In practice this does not matter
usually but some equations have dependencies where this is critical.  We
now ensure that everything is called strictly in the order in which it
is defined.  Thanks to Dileep Menon for spotting this issue.

BUG: Ensure that order of equations is preserved.

---

pysph/cpy/tests/test_transpiler.py
pysph/cpy/transpiler.py

Several math constants are predefined and imported in Cython and
available in OpenCL and we do not need to handle these.  These are
therefore ignored.

Fix bug with defining constants.

---

pysph/cpy/ast_utils.py
pysph/cpy/cython_generator.py
pysph/cpy/tests/py3_code.py
pysph/cpy/tests/test_ast_utils.py
pysph/cpy/tests/test_cython_generator.py
pysph/cpy/tests/test_translator.py
pysph/cpy/types.py

This is entirely optional but at least we support the basic annotations.
Variable annotations are NOT supported, use `declare` instead.  I've
also exposed the basic types in the types module namespace to make it
easy to use the declared types.

Py3 annotations

---

docs/source/design/equations.rst
pysph/base/z_order_gpu_nnps.pyx
pysph/sph/acceleration_eval_cython_helper.py
pysph/sph/acceleration_eval_opencl_helper.py
pysph/sph/equation.py
pysph/sph/tests/test_acceleration_eval.py
pysph/sph/wc/density_correction.py

This is important as KERNEL is used in the CLUDA headers.  So we are
renaming the `KERNEL` argument passed to the `loop_all` and other
methods to be `SPH_KERNEL`.

API: Change KERNEL in equations to SPH_KERNEL.

---

pysph/examples/gas_dynamics/sod_shocktube.py

Although the sod-shocktube problem has a specific set of historical values, the code can be generalized in a few places to suit any 1d shocktube problem with modified parameters

fixed generalization for sod-shocktube example

---

pysph/base/gpu_nnps_base.pxd
pysph/base/gpu_nnps_base.pyx
pysph/base/nnps_base.pxd
pysph/base/nnps_base.pyx

Normally a user gets a very strange error message or a segfault but now
if the particles are diverging and the domain size is increasing more
than twice the last time, it prints a useful warning saying
particles are diverging.  This should hopefully make it easier when
debugging.

Print handy warning when particles are diverging.

---

docs/source/design/equations.rst
docs/source/installation.rst
pysph/sph/acceleration_eval.py
pysph/sph/acceleration_eval_cython.mako
pysph/sph/acceleration_eval_cython_helper.py
pysph/sph/acceleration_eval_opencl.mako
pysph/sph/acceleration_eval_opencl_helper.py
pysph/sph/equation.py
pysph/sph/tests/test_acceleration_eval.py

This allows a user to call arbitrary python code from within a group,
before or after the group executes.  This makes it easy to write
whatever one wants when the framework does not support some features.

Call arbitrary python from a group

---

examples/cpy/README.rst
pysph/cpy/parallel.py
pysph/cpy/tests/test_low_level.py
pysph/cpy/tests/test_parallel.py

The cpy opencl scan does not handle arguments to the segment and output expression correctly. Currently, the scan won't work if the segment or output expression takes an argument which is not also taken by the input expression.
This is the syntax I have in place right now:
```
def input(i, a, b):
...
def segment_expr(i, c, d):
...
def output(i, ... (reserved keywords) ..., e, f):
...
scan = Scan(input=input, output=output, is_segment=segment_expr, ...)
scan(a, b, c, d, e, f)
```
Note the order of the arguments. The input arguments are followed by the segment expression arguments which are then followed by the output arguments. Reserved keywords like item, prev_item need to be inserted before any other arguments for the output function.
I think the following syntax would work better even …

Cython Scan

---

docs/source/design/equations.rst
pysph/cpy/cython_generator.py
pysph/cpy/translator.py
pysph/sph/acceleration_eval_cython.mako
pysph/sph/acceleration_eval_opencl.mako
pysph/sph/acceleration_eval_opencl_helper.py
pysph/sph/equation.py
pysph/sph/integrator_cython.mako
pysph/sph/integrator_cython_helper.py
pysph/sph/integrator_opencl_helper.py
pysph/sph/tests/test_acceleration_eval.py
pysph/sph/tests/test_integrator.py

- Add support for Python integrator steps.  This allows one to define optional `py_stage1` or `py_stage2` which is called with `dest_particle_array, t, dt` and makes a Python call (without any code transpilation).  These are called before `stage1`, `stage2` etc.  One may choose to not have any `stage1` methods too and only the `py_stage` methods.  This will work for both CPU and GPU
backends.  Note that any methods or functions starting with `py_` are not transpiled.
- Support for py_initialize in equations. This allows a user to define a `py_initialize(self, dst, t, dt)`  method in an equation.  This is called as a pure Python (no translation) function before the initialize function is called.

Pure Python integrator stages and equation initializers.

---

examples/cpy/README.rst
examples/cpy/axpb_jit.py
examples/cpy/vm_elementwise_jit.py
pysph/cpy/jit.py
pysph/cpy/parallel.py
pysph/cpy/tests/test_jit.py
pysph/cpy/transpiler.py
pysph/cpy/types.py

This module allows you to use map, reduce and scan without adding type annotations.
I don't know if you wanted this @prabhuramachandran , but I got a little carried away by the idea.

Add jit module to CPy

---

pysph/examples/dam_break_2d.py
pysph/examples/taylor_green.py

Using constants for this is fragile as if we underestimate the size
(especially for the taylor green problem) the code will segfault.  This
is now fixed cleanly.

Use new strides for kernel corrections.

---

docs/source/design/equations.rst
docs/source/reference/equations.rst
pysph/solver/solver.py
pysph/solver/tests/test_solver.py
pysph/sph/acceleration_eval.py
pysph/sph/equation.py
pysph/sph/integrator.py
pysph/sph/integrator_cython.mako
pysph/sph/integrator_cython_helper.py
pysph/sph/integrator_opencl_helper.py
pysph/sph/sph_compiler.py
pysph/sph/tests/test_multi_group_integrator.py

There are schemes where the acceleration terms (the RHS) is different in
each stage of integration.  For example one may predict some properties
and then correct different ones. 
- The Python integrator now performs the `compute_accelerations` and the
API for this now takes an optional index which defaults to zero.  The
compiled integrator simply calls the Python integrator.  A user could
therefore have a `self.compute_accelerations(0)` or
`self.compute_accelerations(1)` to choose different accelerations in
their integrator.  There is also an option called `update_nnps` which
defaults to true in case there is a need to not update nnps.
- The solver does not directly compute the initial acceleration and
instead the integrator has a new method called
`initial_acceleration(t, dt)` that does …

Multi stage equations

---

docs/source/design/equations.rst
pysph/sph/acceleration_eval_cython.mako
pysph/sph/acceleration_eval_opencl.mako
pysph/sph/acceleration_eval_opencl_helper.py
pysph/sph/equation.py
pysph/sph/tests/test_acceleration_eval.py

This basically performs a pairwise initialization, and is called per
destination particle, once per source, but can access source arrays.
This can be handy if one needs to perform initialization pairwise, for
example if one wishes to set some property based on a source property
but without even requiring any neighbors.

Support initialize_pair in equations.

---

pysph/sph/scheme.py

When using 'setup_properties' method in a scheme,
pass the dummy.stride value to '_ensure_properties'
to preserve the info.

preserve stride info in '_ensure_properties'

---

pysph/base/nnps_base.pyx
pysph/tools/cli.py
setup.py

- Fix compilation error with clang 6.x on FreeBSD.  Fixes #152.
- Add /usr/local/include to list of includes.
- Fix pysph test and remove pyzoltan from there.

Fix FreeBSD and other issues

---

pysph/examples/cavity.py
pysph/sph/scheme.py
pysph/sph/wc/transport_velocity.py

The implementation of the boundary condition with the approach of Adami
et al. (2012) uses ghost velocities and it is this velocity that should
be used for the continuity equation and not the usual u, v, and w.  This
is now fixed.

Fix Adami bc

---

pysph/base/nnps_base.pxd
pysph/base/nnps_base.pyx
pysph/base/tests/test_nnps.py

This fixes a massive leak when caching nnps results.  Earlier, the
memory usage would grow without bound because the neighbor lengths were
not reset on each update.  This is now fixed and caching is very
efficient.

BUG: Fix massive leak with caching nnps.

---

docs/source/design/equations.rst
pysph/base/gpu_domain_manager.py
pysph/base/gpu_nnps_base.pyx
pysph/base/nnps_base.pyx
pysph/solver/application.py
pysph/sph/integrator.py
pysph/sph/integrator_cython.mako
pysph/sph/integrator_opencl_helper.py
pysph/sph/tests/test_multi_group_integrator.py
pysph/sph/wc/gtvf.py
pysph/sph/wc/pcisph.py

In the past, the application automatically setup an `nnps.update_domain`
call as a `post_stage` callback.  The `update_domain` sets up any
periodic or mirror ghosts and also updates the cell size based on the
smoothing length.  This is not widely known and a source of some
confusion.  It is also not easy to configure in a scheme for example.
There are cases where there is no need to update the domain.  This API
change makes this an explicit call that users are supposed to add in
their integrators.  Specifically this should be done in the integrator's
`one_timestep` method.  All standard PySPH integrators have been
updated.

API: Integrators explicitly call update_domain.

---

pysph/tools/mayavi_viewer.py

The viewer currently doesn't give any warning for the required filename format. Same is added in the PR.

added check for using arbitrary name in argument

---

docs/source/tutorial/circular_patch_simple.rst
pysph/examples/dam_break_3d.py
pysph/examples/sphysics/case5.py
pysph/examples/sphysics/dam_break.py
pysph/solver/application.py
pysph/tools/mayavi_viewer.py

- Use viridis colormap by default.
- Add an Application.customize_output method. This method can be used to configure the output visualization.  The pysph mayavi viewer now looks for a mayavi_config.py file which can be
generated by overloading Application.customize_output and calling Application._mayavi_config(...).  What this does is to setup the default visualization options so users don't have to do this each time.

Misc viewer improvements

---

docs/source/design/equations.rst
docs/source/design/overview.rst
docs/source/reference/solver.rst
pysph/solver/solver.py
pysph/sph/acceleration_eval_cython.mako
pysph/sph/acceleration_eval_opencl.mako
pysph/sph/bc/inlet.py
pysph/sph/bc/inlet_outlet_manager.py
pysph/sph/integrator_cython.mako
pysph/sph/misc/advection.py
pysph/sph/wc/linalg.py

This is unfortunately necessary as pi is often used as a variable.
Instead users should use M_PI for the value of pi.  Also fix some issues
with the gj_solve function when transpiled to the GPU.

Remove pi as predefined quantity

---

pysph/sph/acceleration_eval_gpu_helper.py
pysph/sph/equation.py
pysph/sph/tests/test_acceleration_eval.py

The issue is that originally before we call `converged`, we'd sync the
equation data from the GPU to the host.  However, `reduce` and
`converged` are pure Python calls on the GPU so if you set `self.conv =
1` or something it sets the Python attribute and not the GPU one.  So
when the converged call synced the value from the GPU it would clobber
the Python attribute.  We therefore no longer do the syncing and it is
up to the user who will call `self._pull` in their reduce or converged
method.  Note that `self._pull` is not available on the CPU which is a
bit of a pain currently but relatively easy to work around. Setting the
GPU attribute is not typical so this is quite acceptable.

Fix subtle issue with automatic syncing on gpu.

---

pysph/tools/mayavi_viewer.py

The earlier approach never set the directory even though it would be
convenient and useful and instead used the files.  We now treat a
directory as such and pass it along. [ci skip]

Cleanup treatment of files and dirs.

---

pysph/base/device_helper.py
pysph/base/tests/test_device_helper.py

On the GPU, calling align with a set of indices, would fail when strided
properties existed.  This is now fixed.

BUG: Align was failing with strided props.

---

docs/source/design/equations.rst
pysph/sph/integrator.py
pysph/sph/tests/test_integrator.py

If the user sets a property called `dt_adapt`, then the minimum of that is
used for the adaptive timestep.  This is convenient for more general
purpose adaptive-timesteps.

Simpler adaptive timestep

---

pysph/examples/flow_past_cylinder_2d.py

When helping a coworker run the flow_past_cylinder_2d example it was noticed that changing the wind tunnel length or width resulted in no change to the simulation. Upon code inspection it was noted that the user input was overwritten by literal values.

Minor Defect Overwriting User Input

---

pysph/solver/solver.py
pysph/solver/tests/test_solver.py

There were cases when the timestep lands very close to a desired output
time and the next output is within a timestep, what happens is that the
next step is then ignored leading to problems.

Fix issue with output_at_times.

---

pysph/solver/application.py
pysph/solver/solver_interfaces.py
pysph/solver/tests/test_solver_utils.py
pysph/solver/utils.py

- Close file handles and logger handlers.
- Remove dirty way of trying for available ports in
MultiprocessingInterface.
- Instead search for suitable ports before starting it.
- Close all interfaces when run completes.
This fixes #247.

Fix issues with open sockets and files.

---

pysph/sph/acceleration_eval_cython.mako
pysph/sph/acceleration_eval_cython_helper.py
pysph/sph/integrator_cython.mako
pysph/sph/integrator_cython_helper.py

Earlier we only used OpenMP for the Equation's `loop` and `loop_all`
methods.  This is not optimal as the number of cores increase.  With
12-20 core machines being routinely available it makes sense to use
OpenMP as much as possible and so now all the equation methods,
`initialize`, `initialize_pair`, `post_loop` in addition to the original
`loop/loop_all` are executed in parallel.  In addition, the integrator
steps are also executed in parallel.  This should give us much better
scale up with more cores.  Note that in the code, the loops do not set
nogil=True since they are already in a block where the gil is released.
This PR requires the latest version of compyle with
https://github.com/pypr/compyle/pull/37 merged.

More OpenMP usage in equations and integrators.

---

docs/source/design/equations.rst
pysph/sph/acceleration_eval.py
pysph/sph/acceleration_eval_cython.mako
pysph/sph/acceleration_eval_cython_helper.py
pysph/sph/acceleration_eval_gpu_helper.py
pysph/sph/equation.py
pysph/sph/tests/test_acceleration_eval.py
pysph/sph/tests/test_acceleration_eval_cython_helper.py

Currently all equations are iterated for all the destination particles. One can iterate either over all real particles or all real and ghost particles.  By passing a `Group`,  `start_idx=n1` and `stop_idx=n2` only `n2 - n1` particles in the destination.  One can also pass a string which is treated as a property/constant which is used to set the values.  This works on the CPU and on the GPU.

Group loop control options

---

docs/source/design/equations.rst
pysph/sph/acceleration_eval.py
pysph/sph/acceleration_eval_cython.mako
pysph/sph/acceleration_eval_cython_helper.py
pysph/sph/acceleration_eval_gpu.mako
pysph/sph/acceleration_eval_gpu_helper.py
pysph/sph/equation.py
pysph/sph/tests/test_acceleration_eval.py

Groups now support a `condition` keyword argument which takes a callable that is
passed `t, dt`.  If it returns `True` the group is executed, else it is not.
This is very convenient for certain schemes. This supported on the CPU and GPU.

Support for defining a conditional group.

---

pysph/base/stratified_sfc_nnps.pxd
pysph/base/stratified_sfc_nnps.pyx
pysph/base/z_order_nnps.pyx

Calculate neighbor boxes for bins instead of particles
Makes stratified SFC about 1.5x faster than octree in case of variable h with max/min ratio of 4

Optimization for stratified SFC NNPS

---

pysph/base/device_helper.py
pysph/examples/_db_geometry.py
pysph/examples/cube.py

This is probably not the best way to fix these issues. 
We should clean up the particle array and device helper so that users don't need to deal with push/pull of data

Fix examples for GPU backends

---

pysph/sph/integrator.py

When running in parallel, a processor may not have a valid dt_cfl
property (when for example it only has solid particles) and this can
cause problems so we guard for this.

BUG: On parallel execution guard for empty dt_cfl.

---

pysph/base/nnps_base.pxd
pysph/base/nnps_base.pyx
pysph/parallel/parallel_manager.pxd
pysph/parallel/parallel_manager.pyx
pysph/sph/scheme.py

These can be set per particle array and are used for parallel execution.
So for example, the solid particles take a lot less computation so
should not be given the same weight as fluid particles.  In this case,
simply add a constant called `lb_weight` to the solid particle arrays
and set the value to 0.1 for example. This will improve the load
balancing.  Each particle array can be given a different weight.
The WCSPH Scheme has been updated to set the weights.  The others
require some investigation.

ENH: Support setting load balancing weights.

---

pysph/tools/ipy_viewer.py

This is annoying and unphysical so we try to reduce the default
animation.

Do not animate the scatter plot.

---

pysph/tools/cli.py
pysph/tools/manage_cache.py

This will show the PySPH and Compyle cache directories and their sizes.
By passing `-c` or `--clear` one can also delete the generated
modules/sources there.

Add a simple `pysph cache` command.

---

.github/workflows/tests.yml
pysph/tools/mesh_tools.pyx

- Fix builds to use PyOpenCL 2021.2.11 for now.
- Also remove some unnecessary imports in mesh_tools.pyx.
- Thanks to @MiloniAtal  for finding the initial issue.

Fix build to use older PyOpenCL

---

.github/workflows/tests.yml
pyproject.toml
pysph/base/gpu_domain_manager.py
pysph/tools/binder.py
requirements-test.txt
requirements.txt
setup.py

- Work around PyOpenCL issue for now: https://github.com/inducer/pyopencl/issues/535
- Add a cron schedule to run the tests so we catch errors due to changes
in upstream packages early.
- Always test with latest cyarray and compyle.
- Improve requirements, we don't need meshio as it is optional but
should test with h5py.
- The requirements.txt does not need to run off master cyarray and
compyle anymore.

Improve build config, work around issues.

---

docs/source/installation.rst

Reason to include: The zoltan AUR package seems to be actively maintained. So, it is likely to not remain broken if there are changes like if the url is updated, at least for arch users.

doc(install): Tip on installation of zoltan from AUR

---

pysph/sph/surface_tension.py

Fixed the implementations of surface tension models from the following papers:
1) M. Shadloo, M. Yildiz, "Numerical modelling of Kelvin-Helmholtz
instability using smoothed particle hydrodynamics", IJNME, 2011
2) Adami et al. "A new surface-tension formulation for multi-phase SPH
using a reproducing divergence approximation", JCP 2010
3) X.Y.Hu, N.A. Adams. "A multi-phase SPH method for macroscopic and
mesoscopic flows", JCP 2006

Corrected Surface tension models 

---

.github/workflows/tests.yml
pysph/base/gpu_nnps_helper.py
pysph/base/tree/point_tree.py
pysph/sph/acceleration_nnps_helper.py

Mako-1.2.0 has removed the `disable_unicode` kwarg this was breaking
pysph.  Also threw in a pip list in the build so we can detect version
changes of packages a bit easier hopefully.

Fix errors due to changes in Mako upstream.

---

.github/workflows/tests.yml

- fixed by using `python setup.py develop` instead of `pip install -e .`
- cause ? : https://github.com/pypa/pip/issues/11467

ci(actions): fix tests failing on windows

---

pysph/examples/dam_break/dam_break_3d_lobovsky.py
pysph/examples/dam_break/db_2d_buchner.py
pysph/examples/dam_break/db_3d_yeh.py
pysph/examples/dam_break_3d.py
pysph/examples/shallow_water/okushiri_tsunami.py
pysph/examples/shallow_water/thacker_basin.py
pysph/examples/sloshing/sloshing_tank_pitch.py

Earlier this was not a problem but a recent PR has introduced group names, so each time the interpolator is constructed, it creates new Equation groups which have their own names and each name is unique, so this means the compilation is performed on each data file being processed. I have changed this for now to reuse the interpolator while post-processing.

Reuse interpolators instead of creating afresh.

---

pysph/tools/mayavi_viewer.py

commit https://github.com/pypr/pysph/commit/7a377d60297df3f4c4bb7518ef90da11128546e9 is reverted.
1. When play trait is set to true and the last file is reached, if the slider is dragged back, the play trait is still true, but the file count is not incremented automatically, i.e it actually stays paused. The reverted commit was actually intended to fix this.
2. In the reverted commit, play trait was set to false when the last file is reached. But it would be better to not change the play trait so that when more files are added and refresh button is pressed, it continues to play.
3. The issue mentioned in the first point is fixed.
3. The play/pause button is always enabled.

Issues with play

---

pysph/sph/acceleration_eval_cython.mako
pysph/sph/acceleration_eval_cython_helper.py
pysph/sph/acceleration_eval_gpu.mako
pysph/sph/tests/test_acceleration_eval.py

If we have a mother group that contains subgroups, then that mother group's `pre`, `post` and `update_nnps` were getting ignored. This is fixed.

bug: mother group's pre and post ignored

---

pysph/sph/acceleration_eval_cython_helper.py

When the root is already in `sys.path` this is not necessary. Adding it is necessary when an editable installation is performed where the `pysph_root` is not in `sys.path`.

No need to add the cython include always.
